title: Your awesome title
author: Rajan
email: rajanhit16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Blogs about Web Technology, web development, front end web development

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  0rajan0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minimal
